[project]
name = "my_agent"
version = "0.1"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["my_agent"]

[tool.setuptools.package-data]
"*" = ["**/*"]